name: Build, Tests, and Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install tarpaulin
      run: cargo install cargo-tarpaulin
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      # TODO: Ignoring main right now because it doesn't do anything important at the moment
      run: cargo tarpaulin --fail-under 100 --exclude-files src/main.rs
