name: Unit Tests and Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # TODO: Will consider re-enabling this once the emulator has advanced to a working state
  Clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Linting and Formatting
        run: cargo clippy
        # cargo fmt --check
  Tests-and-Coverage:
    needs: [Clippy]
    runs-on:                    ubuntu-latest
    container:
      image:                    xd009642/tarpaulin:develop-nightly
      options:                  --security-opt seccomp=unconfined
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo tarpaulin
      # run: cargo tarpaulin --fail-under 100